name: Update Doge Data

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:      # Optional manual trigger

jobs:
  update-doge-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv + Python and activate env
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
        activate-environment: true
        enable-cache: true
    
    - name: Sync from uv.lock
      run: uv sync --frozen # fails CI if the lockfile is out of date

    - name: Run doge-data-download.py with different arguments, create .csv, .xlsx files
      run: |
        cd data
        python doge-data-download.py grants --format csv
        python doge-data-download.py contracts --format csv
        python doge-data-download.py leases --format csv
        cd ../tools/
        python csv_to_excel.py
        cd ..

    - name: Commit and push if there are changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/doge_*_data.json
        git diff --cached --quiet || git commit -m "Automated Doge data update"
        git push

